# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InstaFitness' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'IQKeyboardManagerSwift'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'SideMenu'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'MBProgressHUD'
  pod 'SwiftMessages'
  pod 'SDWebImage'
  pod 'FloatRatingView', '~> 2.0.0'
  pod 'SideMenu'
  pod 'SwiftProgressView'
  pod 'PieCharts'
  pod 'DropDown'




  end
#  # Pods for InstaFitness
#  target 'InstaFitnessTests' do
#    inherit! :search_paths
#    # Pods for testing
#  end
#
#  target 'InstaFitnessUITests' do
#    inherit! :search_paths
#    # Pods for testing
#  end
#
#end
